MSPBSL_Connection5xx Class Reference
MSPBSL_Connection5xx Class Reference
#include <MSPBSL_Connection5xx.h>
Public Member Functions
MSPBSL_Connection5xx (string initString)
virtual ~MSPBSL_Connection5xx (void)
uint16_t massErase (void)
uint16_t RX_Password (void)
uint16_t RX_Password (uint8_t *password)
uint16_t TX_BSL_Version (string &versionString)
uint16_t setPC (uint32_t addr)
uint16_t TX_DataBlock (uint8_t *data, uint32_t startAddr, uint32_t numBytes)
uint16_t RX_DataBlock (uint8_t *data, uint32_t startAddr, uint32_t numBytes)
uint16_t RX_DataBlockFast (uint8_t *data, uint32_t startAddr, uint32_t numBytes)
uint16_t CRC_Check (uint16_t *CRC_Return, uint32_t startAddr, uint16_t numBytes)
uint16_t eraseSegment (uint32_t addr)
uint16_t toggleInfo (void)
uint16_t TX_BufferSize (uint16_t *bufSize)
virtual string getErrorInformation (uint16_t err)
Protected Member Functions
uint16_t sendPacketExpectNothing (uint8_t *packet, uint16_t packetSize)
uint16_t sendPacketExpectMessage (uint8_t *packet, uint16_t packetSize)
Protected Attributes
string bugList
Constructor & Destructor Documentation
MSPBSL_Connection5xx::MSPBSL_Connection5xx (string initString)
MSPBSL_Connection5xx Class Constructor.
Creates a 5/6xx General Connection using the supplied parameters
Parameters:
initString an initialization string for the connection
Returns:
a MSPBSL_Connection5xx class
References BUG_DESIGNATOR, and bugList.
MSPBSL_Connection5xx::~MSPBSL_Connection5xx (void) [virtual]
MSPBSL_Connection5xx Class Destructor.
Member Function Documentation
uint16_t MSPBSL_Connection5xx::massErase (void) [virtual]
The 5/6xx Standard Mass Erase Command
Creates a databuffer containing a standard 5/6xx Mass Erase Command, and passes this on to the Packet Handler layer for sending.
Returns:
the value returned by the connected BSL, or underlying connection layers
Implements MSPBSL_Connection.
Reimplemented in MSPBSL_ConnectionFRAMFamily.
References MASS_ERASE_COMMAND, and sendPacketExpectMessage().
uint16_t MSPBSL_Connection5xx::RX_Password (void) [virtual]
The 5/6xx Standard RX Password Command
Creates a databuffer containing a standard 5/6xx RX Password Command, and passes this on to the Packet Handler layer for sending. Note: This command accepts no parameters as it sends a default (32x 0xFF) password
Returns:
the value returned by the connected BSL, or underlying connection layers
Implements MSPBSL_Connection.
Reimplemented in MSPBSL_Connection5438Family.
Referenced by MSPBSL_Connection5xxUSB::loadRAM_BSL(), and MSPBSL_ConnectionFRAMFamily::massErase().
uint16_t MSPBSL_Connection5xx::RX_Password (uint8_t * password) [virtual]
The 5/6xx Standard RX Password Command
Creates a databuffer containing a standard 5/6xx RX Password Command, and passes this on to the Packet Handler layer for sending.
Parameters:
pass a databuffer containing the device password
Returns:
the value returned by the connected BSL, or underlying connection layers
Implements MSPBSL_Connection.
Reimplemented in MSPBSL_Connection5438Family.
References RX_PASSWORD_COMMAND, and sendPacketExpectMessage().
uint16_t MSPBSL_Connection5xx::TX_BSL_Version (string & versionString) [virtual]
The 5/6xx Standard TX BSL Version Command
Creates a databuffer containing a standard 5/6xx TX BSL Version Command, and passes this on to the Packet Handler layer for sending.
Parameters:
versionString a reference to a string which will store the returned version
Returns:
the value returned by the connected BSL, or underlying connection layers
Implements MSPBSL_Connection.
References ACK, DATA_RESPONSE, GENERAL_BSL_CONNECTION_ERROR, MESSAGE_RESPONSE, OPERATION_SUCCESSFUL, MSPBSL_PacketHandler::RX_Packet(), MSPBSL_Connection::thePacketHandler, TX_BSL_VERSION_COMMAND, and MSPBSL_PacketHandler::TX_Packet().
uint16_t MSPBSL_Connection5xx::setPC (uint32_t addr) [virtual]
The 5/6xx Standard Set PC Command
Creates a databuffer containing a standard 5/6xx Set PC Command, and passes this on to the Packet Handler layer for sending
Parameters:
addr a 32-bit address where the device should begin to execute
Returns:
the result of packet handler's Packet Transmission. Note: This only means the caller knows if the packet was sucessfully sent to the BSL, not whether the desired address is executing correctly
Implements MSPBSL_Connection.
References SET_PC_COMMAND, MSPBSL_Connection::thePacketHandler, and MSPBSL_PacketHandler::TX_Packet().
Referenced by MSPBSL_Connection5xxUSB::loadRAM_BSL().
uint16_t MSPBSL_Connection5xx::TX_DataBlock (uint8_t * data, uint32_t startAddr, uint32_t numBytes) [virtual]
The 5/6xx Standard TX Data Block Command
Sends one or more TX Data Block Commands in order to write all data in the supplied array down to memory as requested
Parameters:
data an array of unsigned bytes to send
startAddr the start address in device memory to begin writing these bytes
numBytes the number of bytes in the array
Returns:
the value returned by the connected BSL, or underlying connection layers
Implements MSPBSL_Connection.
References ACK, DATA_RESPONSE, MSPBSL_PacketHandler::getMaxDataSize(), MESSAGE_RESPONSE, OPERATION_SUCCESSFUL, MSPBSL_PacketHandler::RX_Packet(), MSPBSL_Connection::thePacketHandler, TX_DATA_BLOCK_COMMAND, and MSPBSL_PacketHandler::TX_Packet().
uint16_t MSPBSL_Connection5xx::RX_DataBlock (uint8_t * data, uint32_t startAddr, uint32_t numBytes) [virtual]
The 5/6xx Standard RX Data Block Command
Creates a databuffer containing a standard 5/6xx RX Data Block Command, and passes this on to the Packet Handler layer for sending. Note: This command tells the BSL to Receive a data block, so it will send data from the Host
Parameters:
data an array of unsigned bytes to send
startAddr the start address in device memory to begin writing these bytes
numBytes the number of bytes in the array
Returns:
the value returned by the connected BSL, or underlying connection layers
Implements MSPBSL_Connection.
References ACK, MSPBSL_PacketHandler::getMaxDataSize(), RX_DATA_BLOCK_COMMAND, sendPacketExpectMessage(), and MSPBSL_Connection::thePacketHandler.
uint16_t MSPBSL_Connection5xx::RX_DataBlockFast (uint8_t * data, uint32_t startAddr, uint32_t numBytes)
The 5/6xx Standard RX Data Block Fast Command
Creates a databuffer containing a standard 5/6xx RX Data Block Fast Command, and passes this on to the Packet Handler layer for sending. Note: This command tells the BSL to Receive a data block, so it will send data from the Host
Parameters:
data an array of unsigned bytes to send
startAddr the start address in device memory to begin writing these bytes
numBytes the number of bytes in the array
Returns:
the value returned by the connected BSL, or underlying connection layers Note: This only means the caller knows if the packet was sucessfully sent to the BSL, not whether the data was correctly written
References ACK, MSPBSL_PacketHandler::getMaxDataSize(), RX_DATA_BLOCK_FAST_COMMAND, sendPacketExpectNothing(), and MSPBSL_Connection::thePacketHandler.
Referenced by MSPBSL_Connection5xxUSB::loadRAM_BSL().
uint16_t MSPBSL_Connection5xx::CRC_Check (uint16_t * CRC_Return, uint32_t startAddr, uint16_t numBytes)
The 5/6xx Standard CRC Command
Creates a databuffer containing a standard 5/6xx CRC Command, and passes this on to the Packet Handler layer for sending.
Parameters:
CRC_Return 32bit variable reference in which the CRC value will be placed
startAddr The start address for CRC computation
numBytes The number of bytes to include in CRC computation
Returns:
the value returned by the connected BSL, or underlying connection layers
References ACK, CRC_CHECK_COMMAND, DATA_RESPONSE, GENERAL_BSL_CONNECTION_ERROR, MESSAGE_RESPONSE, OPERATION_SUCCESSFUL, MSPBSL_PacketHandler::RX_Packet(), MSPBSL_Connection::thePacketHandler, and MSPBSL_PacketHandler::TX_Packet().
uint16_t MSPBSL_Connection5xx::eraseSegment (uint32_t addr)
The 5/6xx Standard Erase Segment Command
Creates a databuffer containing a standard 5/6xx Erase Segment Command, and passes this on to the Packet Handler layer for sending
Parameters:
addr a 32-bit address which is in the desired segment to erase
Returns:
the value returned by the connected BSL, or underlying connection layers
References ERASE_SEGMENT_COMMAND, and sendPacketExpectMessage().
uint16_t MSPBSL_Connection5xx::toggleInfo (void)
The 5/6xx Standard Toggle Info Command
Creates a databuffer containing a standard 5/6xx Toggle Info Command, and passes this on to the Packet Handler layer for sending
Returns:
the value returned by the connected BSL, or underlying connection layers
References sendPacketExpectMessage(), and TOGGLE_INFO_LOCK_COMMAND.
uint16_t MSPBSL_Connection5xx::TX_BufferSize (uint16_t * bufSize)
The 5/6xx Standard Get Buffer Size Command
Creates a databuffer containing a standard 5/6xx Get Buffer Size Command, and passes this on to the Packet Handler layer for sending
Parameters:
bufSize a reference to a 16 bit variable in which to write the buffer size
Returns:
the value returned by the connected BSL, or underlying connection layers
References DATA_RESPONSE, MESSAGE_RESPONSE, OPERATION_SUCCESSFUL, MSPBSL_PacketHandler::RX_Packet(), MSPBSL_Connection::thePacketHandler, TX_BUFFER_SIZE_COMMAND, MSPBSL_PacketHandler::TX_Packet(), and UNEXPECTED_VALUE.
string MSPBSL_Connection5xx::getErrorInformation (uint16_t err) [virtual]
An error description function
This function is meant to return a string which fully describes an error code which could be returned from any function within this class
Parameters:
err the 16 bit error code
Returns:
A string describing the error code
Reimplemented from MSPBSL_Connection.
Reimplemented in MSPBSL_Connection5xxUART, MSPBSL_Connection5xxUSB, MSPBSL_Connection5438Family, and MSPBSL_ConnectionFRAMFamily.
uint16_t MSPBSL_Connection5xx::sendPacketExpectNothing (uint8_t * packet, uint16_t packetSize) [protected]
Sends a Data packet and does not expect a message
This function transmits a data packet to the BSL, and will not expect that the BSL replies with a message
Parameters:
packet an array of unsigned bytes containing the data to send
packetSize the number of bytes in the packet
Returns:
TX status as returned by the underlying layers (0 for success)
References MSPBSL_Connection::thePacketHandler, and MSPBSL_PacketHandler::TX_Packet().
Referenced by RX_DataBlockFast(), and MSPBSL_Connection5xxUART::setBaudRate().
uint16_t MSPBSL_Connection5xx::sendPacketExpectMessage (uint8_t * packet, uint16_t packetSize) [protected]
Sends a Data packet and waits for the BSL to reply with a message
This function transmits a data packet to the BSL, and will expect that the BSL should reply with a message
Parameters:
packet an array of unsigned bytes containing the data to send
packetSize the number of bytes in the packet
Returns:
the message or error returned by BSL or underlying layers
References GENERAL_BSL_CONNECTION_ERROR, MESSAGE_RESPONSE, OPERATION_SUCCESSFUL, MSPBSL_PacketHandler::RX_Packet(), MSPBSL_Connection::thePacketHandler, and MSPBSL_PacketHandler::TX_Packet().
Referenced by eraseSegment(), massErase(), RX_DataBlock(), MSPBSL_Connection5438Family::RX_Password(), RX_Password(), and toggleInfo().
Member Data Documentation
string MSPBSL_Connection5xx::bugList [protected]
Referenced by MSPBSL_Connection5xx().
The documentation for this class was generated from the following files:
MSPBSL_Connection5xx.h
MSPBSL_Connection5xx.cpp
Copyright 2012, Texas Instruments Incorporated