MSPBSL_Factory Class Reference
MSPBSL_Factory Class Reference
#include <MSPBSL_Factory.h>
Public Member Functions
MSPBSL_Factory (void)
~MSPBSL_Factory (void)
Static Public Member Functions
static MSPBSL_Connection * getMSPBSL_Connection (string init)
static string expandInitString (string init)
static string errorCode (uint16_t error)
Constructor & Destructor Documentation
MSPBSL_Factory::MSPBSL_Factory (void)
Factory Class Constructor.
Creates a BSL Factory which can supply multiple connections.
Returns:
a MSPBSL_Factory class
MSPBSL_Factory::~MSPBSL_Factory (void)
Factory Class Destructor.
Class Destructor
Member Function Documentation
MSPBSL_Connection * MSPBSL_Factory::getMSPBSL_Connection (string initString) [static]
BSL Connection creator
Creates a BSL connection based on the desired parameters in the init string.
Parameters:
init a string containing configuration parameters
Returns:
a MSPBSL_Connection class
References BUG_SHORT_PASSWORD, expandInitString(), MSPBSL_Connection::setPacketHandler(), MSPBSL_PacketHandler::setPhysicalInterface(), UART_5XX_STRING, UART_FRAM_STRING, and USB_5XX_STRING.
string MSPBSL_Factory::expandInitString (string init) [static]
Expand init string.
Mostly used internally by the factory. This takes a initialization string and returns the expanded value which is used to initialize the sub-layers
Parameters:
init a string containing configuration parameters
Returns:
an expanded parameter string
References REPLACE_LIST_SIZE.
Referenced by getMSPBSL_Connection().
string MSPBSL_Factory::errorCode (uint16_t error) [static]
errorCode.
Used to transform an error code into a human readable form
Parameters:
error a 16 bit error code
Returns:
a string explanation of that error code
The documentation for this class was generated from the following files:
MSPBSL_Factory.h
MSPBSL_Factory.cpp
Copyright 2012, Texas Instruments Incorporated