MSPBSL_CRCEngine Class Reference
MSPBSL_CRCEngine Class Reference
#include <MSPBSL_CRCEngine.h>
Public Member Functions
MSPBSL_CRCEngine (string initString)
~MSPBSL_CRCEngine (void)
void initEngine (uint16_t seed)
void addByte (uint8_t byte)
void addBytes (uint8_t *byte, uint16_t numBytes)
uint16_t getLowByte ()
uint16_t getHighByte ()
uint16_t verify (uint8_t *buf, uint16_t numBytes, uint16_t crc)
Constructor & Destructor Documentation
MSPBSL_CRCEngine::MSPBSL_CRCEngine (string initString)
CRC Engine Class Constructor.
Creates a CRC Engine using the supplied parameters
Parameters:
initString an initialization string for the CRC engine
Returns:
a BSL430_CRC_Engine class
MSPBSL_CRCEngine::~MSPBSL_CRCEngine (void)
CRC Engine Class Destructor.
Member Function Documentation
void MSPBSL_CRCEngine::initEngine (uint16_t seed)
CRC Engine intializaer.
Initializes the CRC engine
Parameters:
seed a 16 bit initialization value
References crc16Value.
Referenced by MSPBSL_PacketHandler5xxUART::RX_Packet(), and MSPBSL_PacketHandler5xxUART::TX_Packet().
void MSPBSL_CRCEngine::addByte (uint8_t byte)
Adds a byte to the ongoing CRC
Parameters:
byte a 8 bit value to add to the CRC
References crc16Value.
Referenced by addBytes().
void MSPBSL_CRCEngine::addBytes (uint8_t * buf, uint16_t numBytes)
Adds an array of bytes to the ongoing CRC
Parameters:
buf a pointer to an 8 bit array to add to the CRC
numBytes the number of bytes to process
References addByte().
Referenced by MSPBSL_PacketHandler5xxUART::TX_Packet(), and verify().
uint16_t MSPBSL_CRCEngine::getLowByte ()
returns the low byte of the 16 bit CRC
Returns:
a 8 bit unsigned value
References crc16Value.
Referenced by MSPBSL_PacketHandler5xxUART::TX_Packet().
uint16_t MSPBSL_CRCEngine::getHighByte ()
returns the high byte of the 16 bit CRC
Returns:
a 8 bit unsigned value
References crc16Value.
Referenced by MSPBSL_PacketHandler5xxUART::TX_Packet().
uint16_t MSPBSL_CRCEngine::verify (uint8_t * buf, uint16_t numBytes, uint16_t crc)
Verifies a databuffers integrity using a 16 bit crc value
Parameters:
buf the data to verify
crc the CRC value to use against the data
Returns:
a non-zero value if the CRC is correct for the data, zero if there is a mis-match
References addBytes(), and crc16Value.
Referenced by MSPBSL_PacketHandler5xxUART::RX_Packet().
The documentation for this class was generated from the following files:
MSPBSL_CRCEngine.h
MSPBSL_CRCEngine.cpp
Copyright 2012, Texas Instruments Incorporated