MSPBSL_Connection5xxUSB Class Reference
MSPBSL_Connection5xxUSB Class Reference
#include <MSPBSL_Connection5xxUSB.h>
Public Member Functions
MSPBSL_Connection5xxUSB (string initString)
virtual ~MSPBSL_Connection5xxUSB (void)
uint16_t loadRAM_BSL (void)
uint16_t loadRAM_BSL (uint8_t *password)
virtual string getErrorInformation (uint16_t err)
Constructor & Destructor Documentation
MSPBSL_Connection5xxUSB::MSPBSL_Connection5xxUSB (string initString)
MSPBSL_Connection5xxUSB Constructor.
Parameters:
initString an initialization string for the connection
Returns:
a MSPBSL_Connection5xxUSB class
MSPBSL_Connection5xxUSB::~MSPBSL_Connection5xxUSB (void) [virtual]
MSPBSL_Connection5xxUSB Destructor.
Member Function Documentation
uint16_t MSPBSL_Connection5xxUSB::loadRAM_BSL (void)
Loads the USB BSL into RAM using the default password
Creates a default 5/6xx password array (32x 0xFF) and calls LoadRAM_BSL with that as a parameter
Returns:
the result of the LoadRAM_BSL function call
uint16_t MSPBSL_Connection5xxUSB::loadRAM_BSL (uint8_t * password)
USB-specific helper function to load the RAM BSL and start it
This function is included in the 5xx USB class as a convenience function it's purpose is to make it simple to unlock a device, load and start the RAM BSL, and re-connect to this RAM BSL
Parameters:
pass the password to submit to the connected device's BSL
Returns:
an unsigned byte describing the success or failure of the entire operation 0: No error, RAM based BSL is loaded, and further communication can continue using this class >0: one or more errors occured
References ACK, ENUMERATE_COMMAND, MSPBSL_PacketHandler::getPhysicalInterface(), MSPBSL_PhysicalInterface::physicalInterfaceCommand(), RAM_BSL_00_05_04_34, MSPBSL_Connection5xx::RX_DataBlockFast(), MSPBSL_Connection5xx::RX_Password(), MSPBSL_Connection5xx::setPC(), and MSPBSL_Connection::thePacketHandler.
string MSPBSL_Connection5xxUSB::getErrorInformation (uint16_t err) [virtual]
An error description function
This function is meant to return a string which fully describes an error code which could be returned from any function within this class
Parameters:
err the 16 bit error code
Returns:
A string describing the error code
Reimplemented from MSPBSL_Connection5xx.
The documentation for this class was generated from the following files:
MSPBSL_Connection5xxUSB.h
MSPBSL_Connection5xxUSB.cpp
Copyright 2012, Texas Instruments Incorporated