MSPBSL_PacketHandler5xxUART Class Reference
MSPBSL_PacketHandler5xxUART Class Reference
#include <MSPBSL_PacketHandler5xxUART.h>
Public Member Functions
MSPBSL_PacketHandler5xxUART (string initString)
virtual ~MSPBSL_PacketHandler5xxUART (void)
uint16_t TX_Packet (uint8_t *buf, uint16_t bufSize)
uint16_t RX_Packet (uint8_t *buf, uint16_t bufSize, uint16_t *numBytesReceived)
uint16_t RX_Packet (uint8_t *buf, uint16_t bufSize)
uint16_t getMaxDataSize ()
virtual string getErrorInformation (uint16_t err)
Constructor & Destructor Documentation
MSPBSL_PacketHandler5xxUART::MSPBSL_PacketHandler5xxUART (string initString)
Object Constructor.
Creates a new MSPBSL_PacketHandler5xxUART object according to the supplied parameters
Parameters:
initString A string containing a list of parameters for this obj
Returns:
a new MSPBSL_PacketHandler5xxUART object
MSPBSL_PacketHandler5xxUART::~MSPBSL_PacketHandler5xxUART (void) [virtual]
MSPBSL_PacketHandler5xxUART Class destructor.
Destructor for this class
Member Function Documentation
uint16_t MSPBSL_PacketHandler5xxUART::TX_Packet (uint8_t * buf, uint16_t bufSize) [virtual]
5xx UART Packet transmit.
Adds the 5xx UART specific header and footer bytes to a buffer, then sends
Parameters:
buf an array of unsigned bytes to send
bufSize the number of bytes in the array
Returns:
0 if success, or other value indicating and error
Implements MSPBSL_PacketHandler.
References ACK, MSPBSL_CRCEngine::addBytes(), MSPBSL_CRCEngine::getHighByte(), MSPBSL_CRCEngine::getLowByte(), HANDLER_OVERHEAD, MSPBSL_CRCEngine::initEngine(), MAX_PACKET_SIZE, MSPBSL_PhysicalInterface::RX_Bytes(), SENT_PACKET_SIZE_EXCEEDS_BUFFER, MSPBSL_PacketHandler::thePhysicalInterface, MSPBSL_PhysicalInterface::TX_Bytes(), and UART_HEADER.
uint16_t MSPBSL_PacketHandler5xxUART::RX_Packet (uint8_t * buf, uint16_t bufSize, uint16_t * numBytesReceived) [virtual]
5xx UART Packet receive.
removes and verifies the 5xx UART specific header and footer bytes from the buffer.
Parameters:
buf an array of unsigned bytes to use as an RX buffer via USB
numBytes the size of the RX buffer
numBytesReceived a reference to an integer to set to the number of RXed bytes
Returns:
0 if sucessful, or a value indicating the error
Implements MSPBSL_PacketHandler.
References ACK, MSPBSL_CRCEngine::initEngine(), RECEIVED_PACKET_SIZE_EXCEEDS_BUFFER, MSPBSL_PhysicalInterface::RX_Bytes(), MSPBSL_PacketHandler::thePhysicalInterface, UART_CHECKSUM_INCORRECT, UART_HEADER, UART_HEADER_INCORRECT, and MSPBSL_CRCEngine::verify().
Referenced by RX_Packet().
uint16_t MSPBSL_PacketHandler5xxUART::RX_Packet (uint8_t * buf, uint16_t bufSize) [virtual]
5xx UART Packet receive.
removes and verifies the 5xx UART specific header and footer bytes from the buffer.
Parameters:
buf an array of unsigned bytes to use as an RX buffer via USB
numBytes the size of the RX buffer
Returns:
0 if sucessful, or a value indicating the error
Implements MSPBSL_PacketHandler.
References RX_Packet().
uint16_t MSPBSL_PacketHandler5xxUART::getMaxDataSize () [virtual]
5xx UART getMaxDataSize
returns the maximum amount of data that can be sent in a packet by this handler
Returns:
the data size
Implements MSPBSL_PacketHandler.
References HANDLER_OVERHEAD, and MAX_PACKET_SIZE.
string MSPBSL_PacketHandler5xxUART::getErrorInformation (uint16_t err) [virtual]
An error description function
This function is meant to return a string which fully describes an error code which could be returned from any function within this class
Parameters:
err the 16 bit error code
Returns:
A string describing the error code
Reimplemented from MSPBSL_PacketHandler.
References UART_CHECKSUM_INCORRECT, and UART_HEADER_INCORRECT.
The documentation for this class was generated from the following files:
MSPBSL_PacketHandler5xxUART.h
MSPBSL_PacketHandler5xxUART.cpp
Copyright 2012, Texas Instruments Incorporated