MSPBSL_PhysicalInterface Class Reference
MSPBSL_PhysicalInterface Class Reference
#include <MSPBSL_PhysicalInterface.h>
Public Member Functions
virtual ~MSPBSL_PhysicalInterface ()
virtual void invokeBSL ()=0
virtual uint16_t TX_Bytes (uint8_t *buf, uint16_t numBytes)=0
virtual uint16_t RX_Bytes (uint8_t *buf, uint16_t numBytes)=0
virtual uint16_t physicalInterfaceCommand (string command)=0
virtual string getErrorInformation (uint16_t err)=0
Constructor & Destructor Documentation
virtual MSPBSL_PhysicalInterface::~MSPBSL_PhysicalInterface () [inline, virtual]
MSPBSL_PhysicalInterface Class destructor.
Destructor for this class
Member Function Documentation
virtual void MSPBSL_PhysicalInterface::invokeBSL () [pure virtual]
Allows each physical interface to decide how it invokes the BSL.
This function is required to do anything, as some BSLs (such as USB) are not invoked by any specific controllable action on the part of the physical interface.
Implemented in MSPBSL_PhysicalInterfaceSerialUART, and MSPBSL_PhysicalInterfaceUSB.
virtual uint16_t MSPBSL_PhysicalInterface::TX_Bytes (uint8_t * buf, uint16_t numBytes) [pure virtual]
Transfers a buffer of bytes.
Each physical interface must impliment its own specific methods for transfering a buffer full of bytes
Parameters:
buf a pointer to an array of bytes to send
numBytes the number of bytes in the array
Returns:
the result of the transfer
Implemented in MSPBSL_PhysicalInterfaceSerialUART, and MSPBSL_PhysicalInterfaceUSB.
Referenced by MSPBSL_PacketHandler5xxUSB::TX_Packet(), and MSPBSL_PacketHandler5xxUART::TX_Packet().
virtual uint16_t MSPBSL_PhysicalInterface::RX_Bytes (uint8_t * buf, uint16_t numBytes) [pure virtual]
Receives a buffer of bytes.
Each physical interface must impliment its own specific methods for receiving a buffer full of bytes
Parameters:
buf a pointer to an array in which to write the bytes
numBytes the number of bytes to receive
Returns:
the result of the transfer
Implemented in MSPBSL_PhysicalInterfaceSerialUART, and MSPBSL_PhysicalInterfaceUSB.
Referenced by MSPBSL_PacketHandler5xxUSB::RX_Packet(), MSPBSL_PacketHandler5xxUART::RX_Packet(), and MSPBSL_PacketHandler5xxUART::TX_Packet().
virtual uint16_t MSPBSL_PhysicalInterface::physicalInterfaceCommand (string command) [pure virtual]
Reserved for Interface Specific commands.
A physical interface can also impliment additional, specific commands
Parameters:
command A string to be interpreted by the specific subclass
Returns:
the result of the command
Implemented in MSPBSL_PhysicalInterfaceSerialUART, and MSPBSL_PhysicalInterfaceUSB.
Referenced by MSPBSL_Connection5xxUSB::loadRAM_BSL(), MSPBSL_ConnectionFRAMFamily::massErase(), and MSPBSL_Connection5xxUART::setBaudRate().
virtual string MSPBSL_PhysicalInterface::getErrorInformation (uint16_t err) [pure virtual]
An error description function
This function is meant to return a string which fully describes an error code which could be returned from any function within this class
Parameters:
err the 16 bit error code
Returns:
A string describing the error code
Implemented in MSPBSL_PhysicalInterfaceSerialUART, and MSPBSL_PhysicalInterfaceUSB.
Referenced by MSPBSL_PacketHandler::getErrorInformation().
The documentation for this class was generated from the following file:
MSPBSL_PhysicalInterface.h
Copyright 2012, Texas Instruments Incorporated