MSPBSL_ConnectionFRAMFamily Class Reference
MSPBSL_ConnectionFRAMFamily Class Reference
#include <MSPBSL_ConnectionFRAMFamily.h>
Public Member Functions
MSPBSL_ConnectionFRAMFamily (string initString)
virtual ~MSPBSL_ConnectionFRAMFamily (void)
uint16_t massErase (void)
virtual string getErrorInformation (uint16_t err)
Constructor & Destructor Documentation
MSPBSL_ConnectionFRAMFamily::MSPBSL_ConnectionFRAMFamily (string initString)
FRAM General Connection Class Constructor.
Creates a 5/6xx General Connection using the supplied parameters
Parameters:
initString an initialization string for the connection
Returns:
a MSPBSL_ConnectionFRAMFamily class
MSPBSL_ConnectionFRAMFamily::~MSPBSL_ConnectionFRAMFamily (void) [virtual]
MSPBSL_ConnectionFRAMFamily Class Destructor.
Member Function Documentation
uint16_t MSPBSL_ConnectionFRAMFamily::massErase (void) [virtual]
A function to send the mass erase command
This function handles the special case of Mass erase for FRAM devices. This means it sends the mass erase, then reinitializes the COM port to 9600 baud then unlocks the BSL again using the default password
Returns:
A string describing the error code
Reimplemented from MSPBSL_Connection5xx.
References ACK, MSPBSL_PacketHandler::getPhysicalInterface(), MSPBSL_PhysicalInterface::physicalInterfaceCommand(), MSPBSL_Connection5xx::RX_Password(), and MSPBSL_Connection::thePacketHandler.
string MSPBSL_ConnectionFRAMFamily::getErrorInformation (uint16_t err) [virtual]
An error description function
This function is meant to return a string which fully describes an error code which could be returned from any function within this class
Parameters:
err the 16 bit error code
Returns:
A string describing the error code
Reimplemented from MSPBSL_Connection5xxUART.
The documentation for this class was generated from the following files:
MSPBSL_ConnectionFRAMFamily.h
MSPBSL_ConnectionFRAMFamily.cpp
Copyright 2012, Texas Instruments Incorporated