MSPBSL_PacketHandler Class Reference
MSPBSL_PacketHandler Class Reference
#include <MSPBSL_PacketHandler.h>
Public Member Functions
virtual ~MSPBSL_PacketHandler ()
virtual uint16_t TX_Packet (uint8_t *buf, uint16_t bufSize)=0
virtual uint16_t RX_Packet (uint8_t *buf, uint16_t bufSize, uint16_t *numBytesReceived)=0
virtual uint16_t RX_Packet (uint8_t *buf, uint16_t bufSize)=0
virtual uint16_t getMaxDataSize ()=0
virtual string getErrorInformation (uint16_t err)
MSPBSL_PhysicalInterface * getPhysicalInterface ()
void setPhysicalInterface (MSPBSL_PhysicalInterface *con)
Protected Attributes
MSPBSL_PhysicalInterface * thePhysicalInterface
Constructor & Destructor Documentation
MSPBSL_PacketHandler::~MSPBSL_PacketHandler (void) [virtual]
MSPBSL_PacketHandler Class destructor.
Destructor for this class
Member Function Documentation
virtual uint16_t MSPBSL_PacketHandler::TX_Packet (uint8_t * buf, uint16_t bufSize) [pure virtual]
Implemented in MSPBSL_PacketHandler5xxUART, and MSPBSL_PacketHandler5xxUSB.
Referenced by MSPBSL_Connection5xx::CRC_Check(), MSPBSL_Connection5xx::sendPacketExpectMessage(), MSPBSL_Connection5xx::sendPacketExpectNothing(), MSPBSL_Connection5xx::setPC(), MSPBSL_Connection5xx::TX_BSL_Version(), MSPBSL_Connection5xx::TX_BufferSize(), and MSPBSL_Connection5xx::TX_DataBlock().
virtual uint16_t MSPBSL_PacketHandler::RX_Packet (uint8_t * buf, uint16_t bufSize, uint16_t * numBytesReceived) [pure virtual]
Implemented in MSPBSL_PacketHandler5xxUART, and MSPBSL_PacketHandler5xxUSB.
Referenced by MSPBSL_Connection5xx::CRC_Check(), MSPBSL_Connection5xx::sendPacketExpectMessage(), MSPBSL_Connection5xx::TX_BSL_Version(), MSPBSL_Connection5xx::TX_BufferSize(), and MSPBSL_Connection5xx::TX_DataBlock().
virtual uint16_t MSPBSL_PacketHandler::RX_Packet (uint8_t * buf, uint16_t bufSize) [pure virtual]
Implemented in MSPBSL_PacketHandler5xxUART, and MSPBSL_PacketHandler5xxUSB.
virtual uint16_t MSPBSL_PacketHandler::getMaxDataSize () [pure virtual]
Implemented in MSPBSL_PacketHandler5xxUART, and MSPBSL_PacketHandler5xxUSB.
Referenced by MSPBSL_Connection5xx::RX_DataBlock(), MSPBSL_Connection5xx::RX_DataBlockFast(), and MSPBSL_Connection5xx::TX_DataBlock().
string MSPBSL_PacketHandler::getErrorInformation (uint16_t err) [virtual]
An error description function
This function is meant to return a string which fully describes an error code which could be returned from any function within this class
Parameters:
err the 16 bit error code
Returns:
A string describing the error code
Reimplemented in MSPBSL_PacketHandler5xxUART, and MSPBSL_PacketHandler5xxUSB.
References GENERAL_PACKET_HANDLER_ERROR, MSPBSL_PhysicalInterface::getErrorInformation(), RECEIVED_PACKET_SIZE_EXCEEDS_BUFFER, SENT_PACKET_SIZE_EXCEEDS_BUFFER, SENT_PACKET_SIZE_ZERO, and thePhysicalInterface.
Referenced by MSPBSL_Connection::getErrorInformation().
MSPBSL_PhysicalInterface * MSPBSL_PacketHandler::getPhysicalInterface ()
Allows an outside class to get access to the Physical Interface.
An outside class might need access to the physical connection used, for lower level manipulation (BSL invoke, etc)
Returns:
the Physical Interface used for packet transmission
References thePhysicalInterface.
Referenced by MSPBSL_Connection5xxUSB::loadRAM_BSL(), MSPBSL_ConnectionFRAMFamily::massErase(), and MSPBSL_Connection5xxUART::setBaudRate().
void MSPBSL_PacketHandler::setPhysicalInterface (MSPBSL_PhysicalInterface * con)
Sets the Physical Interface layer used for sending packets
Sets the Physical Interface layer to be used by this packet handler
Parameters:
con the Physical Interface pointer to use for packet transmission
References thePhysicalInterface.
Referenced by MSPBSL_Factory::getMSPBSL_Connection().
Member Data Documentation
MSPBSL_PhysicalInterface* MSPBSL_PacketHandler::thePhysicalInterface [protected]
Referenced by getErrorInformation(), getPhysicalInterface(), MSPBSL_PacketHandler5xxUSB::RX_Packet(), MSPBSL_PacketHandler5xxUART::RX_Packet(), setPhysicalInterface(), MSPBSL_PacketHandler5xxUSB::TX_Packet(), and MSPBSL_PacketHandler5xxUART::TX_Packet().
The documentation for this class was generated from the following files:
MSPBSL_PacketHandler.h
MSPBSL_PacketHander.cpp
Copyright 2012, Texas Instruments Incorporated