MSPBSL_Connection5xxUART Class Reference
MSPBSL_Connection5xxUART Class Reference
#include <MSPBSL_Connection5xxUART.h>
Public Member Functions
MSPBSL_Connection5xxUART (string initString)
virtual ~MSPBSL_Connection5xxUART (void)
uint16_t setBaudRate (uint32_t baudRate)
virtual string getErrorInformation (uint16_t err)
Constructor & Destructor Documentation
MSPBSL_Connection5xxUART::MSPBSL_Connection5xxUART (string initString)
MSPBSL_Connection5xxUSB Constructor.
Returns:
a MSPBSL_Connection5xxUSB class
MSPBSL_Connection5xxUART::~MSPBSL_Connection5xxUART (void) [virtual]
MSPBSL_Connection5xxUSB Destructor.
Member Function Documentation
uint16_t MSPBSL_Connection5xxUART::setBaudRate (uint32_t baudRate)
Sets the Baud Rate
Parameters:
baudRate the Baud to set as a raw number ie. 9600
Returns:
0 if the set baud rate is successfull, or a non-zero value if error
References ACK, BAUD_115200_NUMBER, BAUD_19200_NUMBER, BAUD_38400_NUMBER, BAUD_4800_NUMBER, BAUD_57600_NUMBER, BAUD_9600_NUMBER, CHANGE_BAUD_RATE_COMMAND, MSPBSL_PacketHandler::getPhysicalInterface(), MSPBSL_PhysicalInterface::physicalInterfaceCommand(), MSPBSL_Connection5xx::sendPacketExpectNothing(), MSPBSL_Connection::thePacketHandler, and UNKNOWN_BAUD_RATE_AS_CONNECTION_PARAM.
string MSPBSL_Connection5xxUART::getErrorInformation (uint16_t err) [virtual]
An error description function
This function is meant to return a string which fully describes an error code which could be returned from any function within this class
Parameters:
err the 16 bit error code
Returns:
A string describing the error code
Reimplemented from MSPBSL_Connection5xx.
Reimplemented in MSPBSL_Connection5438Family, and MSPBSL_ConnectionFRAMFamily.
References UNKNOWN_BAUD_RATE_AS_CONNECTION_PARAM.
The documentation for this class was generated from the following files:
MSPBSL_Connection5xxUART.h
MSPBSL_Connection5xxUART.cpp
Copyright 2012, Texas Instruments Incorporated