MSPBSL_PacketHandler5xxUSB Class Reference
MSPBSL_PacketHandler5xxUSB Class Reference
#include <MSPBSL_PacketHandler5xxUSB.h>
Public Member Functions
MSPBSL_PacketHandler5xxUSB (string initString)
virtual ~MSPBSL_PacketHandler5xxUSB (void)
uint16_t TX_Packet (uint8_t *buf, uint16_t bufSize)
uint16_t RX_Packet (uint8_t *buf, uint16_t bufSize, uint16_t *numBytesReceived)
uint16_t RX_Packet (uint8_t *buf, uint16_t bufSize)
uint16_t getMaxDataSize ()
virtual string getErrorInformation (uint16_t err)
Constructor & Destructor Documentation
MSPBSL_PacketHandler5xxUSB::MSPBSL_PacketHandler5xxUSB (string initString)
MSPBSL_PacketHandler5xxUSB Class Constructor.
Parameters:
initString a string containing configuration parameters
Returns:
a MSPBSL_PacketHandler5xxUSB class
MSPBSL_PacketHandler5xxUSB::~MSPBSL_PacketHandler5xxUSB (void) [virtual]
MSPBSL_PacketHandler5xxUSB Class Destructor.
Member Function Documentation
uint16_t MSPBSL_PacketHandler5xxUSB::TX_Packet (uint8_t * buf, uint16_t numBytes) [virtual]
TX Packet.
Transmits a data packet via USB
Parameters:
buf an array of unsigned bytes to transmit via USB
numBytes the number of bytes contained in the array
Returns:
0 if sucessful, or a value indicating the error
Implements MSPBSL_PacketHandler.
References HANDLER_OVERHEAD, MAX_PACKET_SIZE, SENT_PACKET_SIZE_EXCEEDS_BUFFER, SENT_PACKET_SIZE_ZERO, MSPBSL_PacketHandler::thePhysicalInterface, and MSPBSL_PhysicalInterface::TX_Bytes().
uint16_t MSPBSL_PacketHandler5xxUSB::RX_Packet (uint8_t * buf, uint16_t bufSize, uint16_t * numBytesReceived) [virtual]
RX Packet.
Receives a data packet via USB
Parameters:
buf an array of unsigned bytes to use as an RX buffer via USB
numBytes the size of the RX buffer
numBytesReceived a reference to an integer to set to the number of RXed bytes
Returns:
0 if sucessful, or a value indicating the error
Implements MSPBSL_PacketHandler.
References ACK, MAX_PACKET_SIZE, RECEIVED_PACKET_SIZE_EXCEEDS_BUFFER, MSPBSL_PhysicalInterface::RX_Bytes(), and MSPBSL_PacketHandler::thePhysicalInterface.
Referenced by RX_Packet().
uint16_t MSPBSL_PacketHandler5xxUSB::RX_Packet (uint8_t * buf, uint16_t bufSize) [virtual]
RX Packet.
Receives a data packet via USB
Parameters:
buf an array of unsigned bytes to use as an RX buffer via USB
numBytes the size of the RX buffer
Returns:
0 if sucessful, or a value indicating the error
Implements MSPBSL_PacketHandler.
References RX_Packet().
uint16_t MSPBSL_PacketHandler5xxUSB::getMaxDataSize () [virtual]
5xx USB getMaxDataSize
returns the maximum amount of data that can be sent in a packet by this handler
Returns:
the data size
Implements MSPBSL_PacketHandler.
References HANDLER_OVERHEAD, and MAX_PACKET_SIZE.
string MSPBSL_PacketHandler5xxUSB::getErrorInformation (uint16_t err) [virtual]
An error description function
This function is meant to return a string which fully describes an error code which could be returned from any function within this class
Parameters:
err the 16 bit error code
Returns:
A string describing the error code
Reimplemented from MSPBSL_PacketHandler.
The documentation for this class was generated from the following files:
MSPBSL_PacketHandler5xxUSB.h
MSPBSL_PacketHandler5xxUSB.cpp
Copyright 2012, Texas Instruments Incorporated